baseURL = "/"
languageCode = "en-us"
title = "SketchDev"
theme = "abas"
relativeURLs = true
summaryLength = 40
paginate = 3
[params]
    Description = "Blogs Sketchware Development"

[menu]
  [[menu.main]]
    identifier = "project"
    name = "Projects"
    url = "/project/"
    weight = 100

  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 120
   
    [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 110